create table if not exists sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    real_name varchar(64) not null,
    user_type varchar(32) not null,
    role_code varchar(32) not null default 'student',
    student_id bigint,
    status varchar(32) not null default 'enabled',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

alter table sys_user add column if not exists role_code varchar(32) not null default 'student';

create table if not exists stu_student (
    id bigint generated by default as identity primary key,
    student_no varchar(32) not null unique,
    name varchar(64) not null,
    phone varchar(128),
    email varchar(128),
    grade varchar(16) not null,
    major varchar(64) not null,
    class_name varchar(64) not null,
    political_status varchar(32),
    status varchar(32) not null default 'active',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists cert_template (
    id bigint generated by default as identity primary key,
    template_code varchar(64) not null unique,
    template_name varchar(128) not null,
    template_type varchar(32) not null,
    status varchar(32) not null default 'enabled',
    created_by bigint not null references sys_user(id),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists biz_application (
    id bigint generated by default as identity primary key,
    application_no varchar(64) not null unique,
    application_type varchar(32) not null,
    template_id bigint references cert_template(id),
    applicant_user_id bigint not null references sys_user(id),
    student_id bigint references stu_student(id),
    title varchar(255) not null,
    purpose varchar(255),
    form_data_json text,
    generated_file_id bigint,
    status varchar(32) not null default 'submitted',
    current_approver_id bigint references sys_user(id),
    submitted_at timestamp not null default current_timestamp,
    finished_at timestamp,
    revoke_deadline_at timestamp,
    revoke_reason varchar(255),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists biz_approval_record (
    id bigint generated by default as identity primary key,
    application_id bigint not null references biz_application(id),
    approver_user_id bigint not null references sys_user(id),
    action_type varchar(32) not null,
    action_comment varchar(500),
    before_status varchar(32),
    after_status varchar(32),
    action_time timestamp not null default current_timestamp
);

create table if not exists kb_article (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    summary varchar(500) not null,
    category_label varchar(64) not null,
    publish_status varchar(32) not null,
    version_no varchar(32) not null,
    standard_answer text not null,
    source_file_name varchar(255),
    source_file_id bigint,
    keywords_text varchar(500),
    view_count int not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

alter table kb_article add column if not exists source_file_name varchar(255);
alter table kb_article add column if not exists source_file_id bigint;
alter table kb_article add column if not exists keywords_text varchar(500);
alter table kb_article add column if not exists view_count int not null default 0;

create table if not exists kb_template (
    id bigint generated by default as identity primary key,
    template_name varchar(255) not null,
    category_label varchar(64) not null,
    file_type varchar(16) not null,
    description varchar(500),
    file_id bigint,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists biz_notice (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content varchar(2000) not null,
    audience varchar(255) not null,
    channel_labels varchar(255) not null,
    tag_labels varchar(255),
    delivered_count int not null default 0,
    read_count int not null default 0,
    status varchar(32) not null default 'published',
    publish_at timestamp not null default current_timestamp,
    created_by bigint references sys_user(id),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists biz_notice_read (
    id bigint generated by default as identity primary key,
    notice_id bigint not null references biz_notice(id),
    user_id bigint not null references sys_user(id),
    read_at timestamp not null default current_timestamp,
    unique (notice_id, user_id)
);

create table if not exists sys_audit_log (
    id bigint generated by default as identity primary key,
    actor_user_id bigint references sys_user(id),
    actor_name varchar(128) not null,
    module_name varchar(64) not null,
    action_text varchar(500) not null,
    result_text varchar(32) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists biz_honor (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    owner_name varchar(128) not null,
    owner_user_id bigint,
    honor_scope varchar(32) not null,
    honor_year varchar(8) not null,
    category_label varchar(64) not null,
    story varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create index if not exists idx_biz_application_student_status on biz_application(student_id, status);
create index if not exists idx_biz_application_approver_status on biz_application(current_approver_id, status);
create index if not exists idx_biz_application_applicant on biz_application(applicant_user_id);
create index if not exists idx_kb_article_category_status on kb_article(category_label, publish_status);
create index if not exists idx_kb_template_category on kb_template(category_label);
create index if not exists idx_biz_notice_status_publish on biz_notice(status, publish_at);
create index if not exists idx_sys_audit_log_created on sys_audit_log(created_at);
create index if not exists idx_biz_honor_scope on biz_honor(honor_scope);
