create table if not exists sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    real_name varchar(64) not null,
    user_type varchar(32) not null,
    student_id bigint,
    status varchar(32) not null default 'enabled',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists stu_student (
    id bigint generated by default as identity primary key,
    student_no varchar(32) not null unique,
    name varchar(64) not null,
    phone varchar(128),
    email varchar(128),
    grade varchar(16) not null,
    major varchar(64) not null,
    class_name varchar(64) not null,
    political_status varchar(32),
    status varchar(32) not null default 'active',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists cert_template (
    id bigint generated by default as identity primary key,
    template_code varchar(64) not null unique,
    template_name varchar(128) not null,
    template_type varchar(32) not null,
    status varchar(32) not null default 'enabled',
    created_by bigint not null references sys_user(id),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists biz_application (
    id bigint generated by default as identity primary key,
    application_no varchar(64) not null unique,
    application_type varchar(32) not null,
    template_id bigint references cert_template(id),
    applicant_user_id bigint not null references sys_user(id),
    student_id bigint references stu_student(id),
    title varchar(255) not null,
    purpose varchar(255),
    form_data_json text,
    generated_file_id bigint,
    status varchar(32) not null default 'submitted',
    current_approver_id bigint references sys_user(id),
    submitted_at timestamp not null default current_timestamp,
    finished_at timestamp,
    revoke_deadline_at timestamp,
    revoke_reason varchar(255),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    is_deleted smallint not null default 0
);

create table if not exists biz_approval_record (
    id bigint generated by default as identity primary key,
    application_id bigint not null references biz_application(id),
    approver_user_id bigint not null references sys_user(id),
    action_type varchar(32) not null,
    action_comment varchar(500),
    before_status varchar(32),
    after_status varchar(32),
    action_time timestamp not null default current_timestamp
);

create index if not exists idx_biz_application_student_status on biz_application(student_id, status);
create index if not exists idx_biz_application_approver_status on biz_application(current_approver_id, status);
create index if not exists idx_biz_application_applicant on biz_application(applicant_user_id);
